const zamanVerisi = {
    // 1990
    "1990-01-01": "Doksanlı yılların ilk sabahı. Türkiye'de kar yağışlı bir gün ve yeni bir on yıla dair büyük umutlar.",
    "1990-02-11": "Nelson Mandela, 27 yıl hapis hayatından sonra özgürlüğüne kavuştu. Dünya için tarihi bir an.",
    "1990-03-01": "Türkiye'nin ilk özel televizyon kanalı Star 1 (Magic Box) test yayınlarına başladı.",
    "1990-05-22": "Kuzey ve Güney Yemen birleşerek Yemen Cumhuriyeti'ni kurdu.",
    "1990-06-08": "İtalya 90 Dünya Kupası başladı. 'Un'estate italiana' şarkısı her yerde yankılanıyor.",
    "1990-08-02": "Irak, Kuveyt'i işgal etti. Körfez Savaşı'nın fitili ateşlendi.",
    "1990-10-03": "Doğu ve Batı Almanya birleşti. Berlin Duvarı'nın yıkılışından sonra Avrupa yeniden şekilleniyor.",
    "1990-11-21": "Nintendo, efsanevi oyun konsolu Super Famicom'u (SNES) piyasaya sürdü.",
    "1990-12-09": "Lech Walesa, Polonya'nın halk oyuyla seçilen ilk başkanı oldu.",
    "1990-12-24": "Nartugan; kış gündönümü. Gece ile gündüzün savaşında ışık kazanmaya başlıyor.",

    // 1991
    "1991-01-17": "Çöl Fırtınası Operasyonu başladı. Türkiye gece boyu CNN üzerinden savaşı canlı izledi.",
    "1991-03-16": "Halepçe Katliamı'nın yıldönümünde hüzün hakim.",
    "1991-04-12": "Türkiye'de terörle mücadele yasası yürürlüğe girdi, siyasi yasaklar kısmen esnetildi.",
    "1991-05-21": "Hindistan Başbakanı Rajiv Gandhi bir suikast sonucu hayatını kaybetti.",
    "1991-07-01": "Varşova Paktı resmen dağıldı. Soğuk Savaş'ın son kalesi de yıkıldı.",
    "1991-08-25": "Linus Torvalds, Linux çekirdeğinin ilk sürümünü duyurdu. Dijital devrim başlıyor.",
    "1991-10-20": "Türkiye'de genel seçimler yapıldı. Koalisyonlar dönemi kapıda.",
    "1991-11-24": "Efsanevi solist Freddie Mercury hayata gözlerini yumdu. Müzik dünyası yasta.",
    "1991-12-08": "SSCB resmen dağıldı. Bağımsız Devletler Topluluğu kuruldu.",
    "1991-12-25": "Mikhail Gorbachev istifa etti, Kremlin'de Sovyet bayrağı son kez indirildi.",

    // 1992
    "1992-01-15": "Avrupa topluluğu Slovenya ve Hırvatistan'ın bağımsızlığını tanıdı.",
    "1992-02-25": "Hocalı Katliamı yaşandı. Türk dünyası büyük bir acıyla sarsıldı.",
    "1992-03-13": "Erzincan depremi meydana geldi. Türkiye yaralarını sarmaya çalışıyor.",
    "1992-05-19": "Gençlik ve Spor Bayramı. Doksanların coşkulu stat gösterileri devam ediyor.",
    "1992-06-03": "Rio de Janeiro'da Dünya Çevre Zirvesi başladı.",
    "1992-07-25": "Barcelona Olimpiyat Oyunları başladı. 'Dream Team' basketbol sahnelerinde fırtına gibi esiyor.",
    "1992-09-01": "Türkiye'de Show TV yayın hayatına başladı.",
    "1992-10-20": "Tarkan'ın ilk albümü 'Yine Sensiz' çıktı. 'Kıl Oldum Abi' her yerde çalıyor.",
    "1992-11-03": "Bill Clinton, ABD Başkanı seçildi.",
    "1992-12-03": "Dünyadaki ilk SMS (Kısa mesaj) gönderildi: 'Merry Christmas'.",

    // 1993
    "1993-01-24": "Gazeteci yazar Uğur Mumcu suikasta kurban gitti. Türkiye ayağa kalktı.",
    "1993-02-26": "Dünya Ticaret Merkezi'ne ilk bombalı saldırı düzenlendi.",
    "1993-04-17": "8. Cumhurbaşkanı Turgut Özal hayatını kaybetti. Türkiye'de bir dönem kapandı.",
    "1993-05-16": "Süleyman Demirel, Türkiye'nin 9. Cumhurbaşkanı seçildi.",
    "1993-06-25": "Tansu Çiller, Türkiye'nin ilk kadın Başbakanı oldu.",
    "1993-07-02": "Sivas Madımak Oteli olayı yaşandı. Toplumsal hafızada derin bir yara.",
    "1993-08-15": "Kanal D yayın hayatına başladı.",
    "1993-09-13": "Yaser Arafat ve İzak Rabin, Oslo Barış Anlaşması'nı imzaladı.",
    "1993-10-29": "Cumhuriyetin 70. yılı büyük kutlamalarla geçti.",
    "1993-12-11": "Steven Spielberg'in başyapıtı Schindler'in Listesi vizyona girdi.",

    // 1994
    "1994-01-05": "Ekonomik kriz sinyalleri; dolar bir gecede büyük sıçrama yaptı.",
    "1994-03-27": "Yerel seçimlerde Refah Partisi İstanbul ve Ankara'da büyük başarı kazandı.",
    "1994-04-05": "Kurt Cobain (Nirvana) trajik bir şekilde hayatını kaybetti. Bir neslin idolü gitti.",
    "1994-05-10": "Nelson Mandela, Güney Afrika'nın ilk siyah başkanı olarak yemin etti.",
    "1994-06-17": "Dünya Kupası ABD'de başladı. Maradona'nın son turnuvası.",
    "1994-07-17": "Brezilya, penaltılarla İtalya'yı yenerek Dünya Şampiyonu oldu.",
    "1994-09-22": "Efsanevi dizi 'Friends' ilk bölümüyle yayınlanmaya başladı.",
    "1994-11-01": "Serdar Ortaç'ın 'Karabiberim' klibi doksanların pop kültürüne damga vurdu.",
    "1994-11-22": "Sega Saturn oyun konsolu Japonya'da satışa çıktı.",
    "1994-12-03": "Sony, ilk PlayStation'ı piyasaya sürerek oyun dünyasını sonsuza dek değiştirdi.",

    // 1995
    "1995-01-17": "Japonya'nın Kobe şehrinde büyük bir deprem meydana geldi.",
    "1995-03-12": "Gazi Mahallesi olayları patlak verdi.",
    "1995-04-19": "Oklahoma City saldırısı; ABD tarihinin o güne kadarki en büyük terör eylemi.",
    "1995-07-11": "Srebrenitsa Katliamı. İnsanlık tarihinin en karanlık sayfalarından biri.",
    "1995-08-24": "Windows 95 piyasaya sürüldü. Başlat menüsü hayatımıza girdi.",
    "1995-10-24": "Türkiye, Avrupa ile Gümrük Birliği anlaşmasına son şeklini verdi.",
    "1995-11-04": "İsrail Başbakanı İzak Rabin bir suikast sonucu öldürüldü.",
    "1995-11-22": "Toy Story (Oyuncak Hikayesi) vizyona girdi; ilk tamamen bilgisayar yapımı film.",
    "1995-12-24": "Türkiye'de erken genel seçimler yapıldı.",
    "1995-12-25": "Kardak Kayalıkları krizi başladı. Türkiye ve Yunanistan savaşın eşiğine geldi.",

    // 1996
    "1996-01-31": "Kardak kayalıklarına Türk SAT komandoları çıktı, bayrak dikildi.",
    "1996-02-10": "Deep Blue bilgisayarı, satranç şampiyonu Kasparov'u ilk kez yendi.",
    "1996-03-13": "İskoçya'da Dunblane katliamı yaşandı.",
    "1996-05-15": "Galatasaray, Türkiye Kupası'nı kazandı; Fatih Terim dönemi başlıyor.",
    "1996-07-05": "Koyun Dolly klonlandı; tarihteki ilk klonlanmış memeli.",
    "1996-07-19": "Atlanta Olimpiyat Oyunları başladı. Muhammed Ali meşaleyi yaktı.",
    "1996-09-13": "Ünlü rapçi Tupac Shakur hayatını kaybetti.",
    "1996-10-31": "Michael Jackson, 'HIStory' turnesi kapsamında dev konserler veriyor.",
    "1996-11-03": "Susurluk Kazası meydana geldi. Devlet-mafya-siyaset üçgeni tartışılıyor.",
    "1996-12-31": "Yeni yıla girerken 'Sürekli Aydınlık İçin Bir Dakika Karanlık' eylemleri planlanıyor.",

    // 1997
    "1997-01-15": "Prenses Diana, Angola'da kara mayınlarına karşı yürüyüş yaptı.",
    "1997-02-28": "Türkiye'de 'Post-modern darbe' olarak adlandırılan MGK kararları açıklandı.",
    "1997-04-01": "Mavi Hat (Blue Stream) projesi için ilk adımlar atıldı.",
    "1997-05-11": "IBM'in Deep Blue bilgisayarı Kasparov'u rövanşta da mağlup etti.",
    "1997-06-26": "J.K. Rowling'in ilk Harry Potter kitabı yayımlandı.",
    "1997-07-01": "Hong Kong, İngiltere'den Çin'e devredildi.",
    "1997-08-31": "Prenses Diana Paris'te trajik bir trafik kazasında hayatını kaybetti.",
    "1997-09-05": "Rahibe Teresa vefat etti.",
    "1997-11-12": "Eurovision şampiyonumuz Şebnem Paker'in 'Dinle' şarkısı hala kulaklarda.",
    "1997-12-19": "Titanic filmi vizyona girdi. Sinema tarihinin en büyük gişe rekoru yolda.",

    // 1998
    "1998-01-12": "Avrupa'da insan klonlanması yasaklandı.",
    "1998-02-07": "Kış Olimpiyat Oyunları Japonya'nın Nagano kentinde başladı.",
    "1998-04-10": "Hayırlı Cuma Anlaşması ile Kuzey İrlanda'da barış sağlandı.",
    "1998-05-14": "Frank Sinatra hayata gözlerini yumdu.",
    "1998-06-10": "Dünya Kupası Fransa'da başladı. Ricky Martin 'La Copa de la Vida' diyor.",
    "1998-07-12": "Fransa kendi evinde Dünya Şampiyonu oldu. Zidane devleşti.",
    "1998-09-04": "Google, Larry Page ve Sergey Brin tarafından resmen kuruldu.",
    "1998-10-29": "Cumhuriyetin 75. yılı tüm yurtta görkemli törenlerle kutlandı.",
    "1998-11-21": "Zelda: Ocarina of Time oyunu çıktı; oyun tarihinin en yüksek puanlı yapımı.",
    "1998-12-31": "Avrupa para birimi Euro'nun piyasaya sürülmesine bir gün kaldı.",

    // 1999
    "1999-01-01": "Euro para birimi resmen yürürlüğe girdi (bankacılık ve transferlerde).",
    "1999-02-16": "PKK lideri Abdullah Öcalan Türkiye'ye getirildi.",
    "1999-03-24": "NATO, Kosova operasyonunu (Müttefik Güç) başlattı.",
    "1999-03-31": "The Matrix filmi vizyona girdi. Gerçeklik algımız değişiyor.",
    "1999-05-17": "Galatasaray üst üste 4. kez şampiyon oldu.",
    "1999-08-11": "Son yüzyılın son tam güneş tutulması Türkiye'den izlendi.",
    "1999-08-17": "Marmara Depremi. Türkiye tarihinin en büyük felaketlerinden birini yaşadı.",
    "1999-10-12": "Dünya nüfusu resmen 6 milyara ulaştı.",
    "1999-11-12": "Düzce Depremi meydana geldi.",
    "1999-12-31": "Y2K korkusuyla geçen son gece. Milenyum büyük bir coşkuyla başladı."
};
